# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title rcpp_simulate
#' @description
#' Simulate a network model
#' @name rcpp_simulate
#' @param
#' @examples
#' rcp
NULL

rcpp_estimate_model_ml_Hway <- function(RNETWORK, rsamp_num, rburnin, rinterval, rmodel_dim, model_terms, rnum_nodes, rnum_layers, rhighest_order, random_seeds, g) {
    .Call(`_mlnetseparable_rcpp_estimate_model_ml_Hway`, RNETWORK, rsamp_num, rburnin, rinterval, rmodel_dim, model_terms, rnum_nodes, rnum_layers, rhighest_order, random_seeds, g)
}

rcpp_estimate_model_ml <- function(RNETWORK, rNR_tol, rNR_max, rMCMLE_max, rsamp_num, rburnin, rinterval, rmodel_dim, model_terms, rnum_nodes, rnum_layers, rcheck_chull, random_seeds, g) {
    .Call(`_mlnetseparable_rcpp_estimate_model_ml`, RNETWORK, rNR_tol, rNR_max, rMCMLE_max, rsamp_num, rburnin, rinterval, rmodel_dim, model_terms, rnum_nodes, rnum_layers, rcheck_chull, random_seeds, g)
}

rcpp_estimate_model <- function(RNETWORK, rNR_tol, rNR_max, rMCMLE_max, rsamp_num, rburnin, rinterval, rmodel_dim, model_terms, rnum_nodes, bmemb, rnum_blocks, rcheck_chull) {
    .Call(`_mlnetseparable_rcpp_estimate_model`, RNETWORK, rNR_tol, rNR_max, rMCMLE_max, rsamp_num, rburnin, rinterval, rmodel_dim, model_terms, rnum_nodes, bmemb, rnum_blocks, rcheck_chull)
}

#' 
#' @export
rcpp_simulate <- function(rsamp_num, rburnin, rinterval, rmodel_dim, model_terms, rnum_nodes, bmemb, rnum_blocks, rtheta) {
    .Call(`_mlnetseparable_rcpp_simulate`, rsamp_num, rburnin, rinterval, rmodel_dim, model_terms, rnum_nodes, bmemb, rnum_blocks, rtheta)
}

#' @title rcpp_simulate_ml
#' @description
#' Simulate a multilayer network model
#' @name rcpp_simulate_ml
#' @param
#' @examples
#' rcpp_simulate_ml(1,100,1,2,c("withinlayer","crosslayer"),3,2,c(0.4,0.7))
#' 
#' @export
rcpp_simulate_ml <- function(rsamp_num, rburnin, rinterval, rmodel_dim, model_terms, rnum_nodes, rnum_layers, rtheta, rand_seed, g) {
    .Call(`_mlnetseparable_rcpp_simulate_ml`, rsamp_num, rburnin, rinterval, rmodel_dim, model_terms, rnum_nodes, rnum_layers, rtheta, rand_seed, g)
}

rcpp_simulate_ml_Hway <- function(rsamp_num, rburnin, rinterval, rmodel_dim, model_terms, rnum_nodes, rnum_layers, highest_order, rtheta, rand_seed, g) {
    .Call(`_mlnetseparable_rcpp_simulate_ml_Hway`, rsamp_num, rburnin, rinterval, rmodel_dim, model_terms, rnum_nodes, rnum_layers, highest_order, rtheta, rand_seed, g)
}

#' @title rcpp_simulate_ml_Hway_suffstats
#' @description
#' Simulate a multilayer network model and print out sufficient statistics
#' @name rcpp_simulate_ml_Hway_suffstats
#' @param
#' @examples
#' rcpp_simulate_ml_Hway_suffstats(1,100,1,2,c("withinlayer","crosslayer"),3,2,2, c(0.4,0.7),123,1)
#' 
#' @export
rcpp_simulate_ml_Hway_suffstats <- function(rsamp_num, rburnin, rinterval, rmodel_dim, model_terms, rnum_nodes, rnum_layers, highest_order, rtheta, rand_seed, g) {
    .Call(`_mlnetseparable_rcpp_simulate_ml_Hway_suffstats`, rsamp_num, rburnin, rinterval, rmodel_dim, model_terms, rnum_nodes, rnum_layers, highest_order, rtheta, rand_seed, g)
}

#' @title rcpp_simulate_ml_suffstats
#' @description
#' Simulate a multilayer network model and print out sufficient statistics
#' @name rcpp_simulate_ml_suffstats
#' @param
#' @examples
#' rcpp_simulate_ml_suffstats(1,100,1,2,c("withinlayer","crosslayer"),3,2, c(0.4,0.7),123,1)
#' 
#' @export
rcpp_simulate_ml_suffstats <- function(rsamp_num, rburnin, rinterval, rmodel_dim, model_terms, rnum_nodes, rnum_layers, rtheta, rand_seed, g) {
    .Call(`_mlnetseparable_rcpp_simulate_ml_suffstats`, rsamp_num, rburnin, rinterval, rmodel_dim, model_terms, rnum_nodes, rnum_layers, rtheta, rand_seed, g)
}

#' @title rcpp_exact_simulate_ml
#' @description
#' Simulate a multilayer network model by its joint density
#' @name rcpp_exact_simulate_ml
#' @param
#' @examples
#' rcpp_exact_simulate_ml(1,1,3,7,rep("ml_order2",7),10,3,c(0,0.693,0.693,0,0.693,0,0),23333)
#'
#' @export
rcpp_exact_simulate_ml <- function(rsamp_num, rburnin, rinterval, rmodel_dim, model_terms, rnum_nodes, rnum_layers, rtheta, rand_seed) {
    .Call(`_mlnetseparable_rcpp_exact_simulate_ml`, rsamp_num, rburnin, rinterval, rmodel_dim, model_terms, rnum_nodes, rnum_layers, rtheta, rand_seed)
}

rcpparma_hello_world <- function() {
    .Call(`_mlnetseparable_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_mlnetseparable_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_mlnetseparable_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_mlnetseparable_rcpparma_bothproducts`, x)
}

